name: "Haskell"

"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - app/home-api-server/**
      - common/**
      - config/**
      - lib/**
      - Setup.hs
      - stack.yaml
      - stack.yaml.lock

concurrency:
  group: "haskell-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-24.04-arm

    steps:
      - name: "Install system dependencies"
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: Build
        uses: mbg/actions/stack/build@v0.4
        with:
          upload-docs: true
